### GET Visualizar materias
GET http://localhost:3000/materias


### POST criar materia
POST http://localhost:3000/materias
Content-Type: application/json
{
    "nome": "Sistema Digitais",
    "data_inicio": "2023-07-01",
    "data_fim": null,
    "origem": "IESB"
}


### DELETE deletar materia por id
DELETE http://localhost:3000/materias
Content-Type: application/json
{
    "id_materia": 9
}


### tag da materia
GET http://localhost:3000/materias/1/tags


### inserir tag na materia
POST http://localhost:3000/materias/2/tags
Content-Type: application/json

{
    "nome_tag": "Matemática"
}

###